### ISSUE TITLE
How to Build the Styleguide

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#1]
This is an issue to tease out how we will build the styleguide (and I guess where development and discussion about this should happen - here or Drupal.org).

In the short term, and just so we can get moving, I am going to start working with the following methodology.

Create a prototype of each feature using PHP, e.g. 
- header
- footer
- teaser view mode
- node full view mode
- etc

We can then make up sample pages using these PHP files as includes.

This is a basic methodology, but does allow us to get rendered HTML so we can start adding the CSS and JS that will be needed. It also means we can work out issues with this approach so we will have a clearer understanding of what we need when we get to DrupalCon in Vienna.

I am going to work on the premise of using the same classes that Drupal core outputs, such as:

```
<article role="article" class="node node--type-feature-article node--promoted node--view-mode-full clearfix">
  <div class="node__content clearfix">
    // content goes here
  </div>
</article>
```
If we decide to change classes, it shouldn't be too much of an effort to rework them later.

===
If anyone has any other ideas (I'm sure lots of people have much better ones), please add your comments. If we have a better way of doing things, I have a big delete button and I'm not afraid to use it!

**Comment by ckrina** [comment]
+1 to this approach, it makes sense!

**Comment by lauriii** [comment]
During DrupalCon we decided to use KSS to build the style guide. I just updated the readme with the instructions so I'm closing this.
