### ISSUE TITLE
Layout widths are different on recipe and recipe listing page

### ISSUE THREAD

**Issue by thamas** [lauriii/umami#106]
…and recipe listing is narrower than the header too.

![screenshot-2017-11-18 17-11-05](https://user-images.githubusercontent.com/1244043/32982393-29fad06c-cc84-11e7-901b-471ef39a4822.png)

**Comment by markconroy** [comment]
Hi @thamas 

I think this should be fixed from some rework that I did on it tonight.

See here: https://github.com/lauriii/umami/commit/e39d49fe8128d4f8be62d709d1baea0256b1c0fd

**Comment by thamas** [comment]
Hi @markconroy 

Should it be seen at the platform site already? I've checked just that and the header elements still "jump" a little when I switch to the recipes listing page from a recipe or from the homepage. It is not the case if I switch to the homepage from a recipe.

**Comment by markconroy** [comment]
I think that was only put on the platform site today, when Gareth did the `composer update` and pushed.

Can you check again please?

**Comment by thamas** [comment]
Yeah, it's ok now! Thanks!
