### ISSUE TITLE
Components: Banner for recipes listing page (and articles listing page)

### ISSUE THREAD

**Issue by kjays** [lauriii/umami#107]
We need to create the Banner for the very top of recipes page. Roy's suggestion was to use a custom block type for this, something he'd done on a recent project. It demonstrates custom blocks with fields and allows a distinct background image to be uploaded. Having a distinct image is helpful because our content model only has field_image on recipes and the image used for a 3 x 2 representation will likely not be suitable for overlaying text.

I'll need to catch up with @gareth-fivemile because whilst I believe we can easily have custom block config in our profile, it won't easily install the sample content to that block.

So that work can progress on the theming I am going to try out creating the config for this feature, committing that into the profile but perhaps place the resulting HTML into either a block in code or template file so that we can continue with theming. This also gives us time to change our minds on how we want this to work if there are other points of view to consider.

**Comment by ckrina** [comment]
It's been addressed.
