### ISSUE TITLE
Component:  Primary tabs theming

### ISSUE THREAD

**Issue by mariohernandez** [lauriii/umami#108]
Theme Drupal's primary tabs block so they are presentable, visually appealing and match the overall theme.

**Comment by markconroy** [comment]
Hi Mario,

I think the primary tabs are already done:
![screen shot 2017-11-27 at 19 21 30](https://user-images.githubusercontent.com/2183332/33284849-5305e188-d3a8-11e7-95cf-988db712fc35.png)

**Comment by ckrina** [comment]
Agree, it's done! Let's close fixed issues.
