### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by ckrina** [lauriii/umami#109]
Not sure if we want to change the Drupal's default. Opening it for discussion.

**Comment by thamas** [comment]
I think we should! So we demonstrate that it can be changed too. 

Maybe it can be a cooking Druplicon to make Drupal still recognizable… ;)

**Comment by kjays** [comment]
It's a good idea to change it I think :)

I'll definitely start thinking about some ideas as well.

**Comment by thamas** [comment]
https://montpellier2015.drupaldays.org/sites/all/themes/custom/ddd15/logo.png :)

**Comment by fuzzbomb** [comment]
I love the Druplicon Chef!

Ideas:

- Favicon has very limited space.  Is there enough room for the Drupal Chef's hat?
- Use the orange-red colour from the site logo. A red Druplicon would be cool, with or without the hat ;-)
- Larger icons for smartphones, they will have enough room for the Drupal Chef.
- The Drupal Chef doesn't actually appear in the page design, unlike Bartik.  The orange-red U from the site logo could be a good alternative icon.  It would match something from the web page header at least.

**Comment by ckrina** [comment]
I'm not a big fan of Druplicon-with-stuff logos, so my vote would go to something like the last proposal : )

**Comment by markconroy** [comment]
https://www.drupal.org/project/drupal/issues/2938190
