### ISSUE TITLE
Media Queries best practices approach

### ISSUE THREAD

**Issue by ckrina** [lauriii/umami#111]
Discussed on the call: any idea about the best approach.

**Comment by thamas** [comment]
Just collected our findings from the agenda and from Slack:

a) Code at top of file and media queries overrides at bottom?
b) Media queries inline with each component/selector/class that needs them?
c) CSS formatting guidelines are not clear on this point - https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines

Bartik theme seems to favour option B - e.g. in tabs.css

Media queries are mentioned here: https://www.drupal.org/docs/develop/standards/css/css-formatting-guidelines Doesn’t exactly answer our question.

This places media queries to the state group, similar to eg. pseudo-classes. We write pseudo class version right after after the selector definition so it seems to be logical to write a related query to there too. :)
https://www.drupal.org/docs/develop/standards/css/css-architecture-for-drupal-8

**Comment by ckrina** [comment]
Thanks @thamas !

Then it looks like placing media queries after each block is the best approach.

Any other opinion before closing this?

**Comment by thamas** [comment]
Nothing more. :)
