### ISSUE TITLE
Layout margin / padding

### ISSUE THREAD

**Issue by thamas** [lauriii/umami#113]
When the screen is narrower than the max with of the `.container` there is no default space between the edge of the screen and the content. 

Eg.: https://monosnap.com/file/tVswF33hAyZfP5UnK8nHXj1rJwio4C#

We should decide if we add margin/padding to the `.container` or we mange this in component level for every related component. (It is done here and here but not everywhere.)

**Comment by tomphippen** [comment]
Hi @thamas 

I've fixed this locally on just the `.region-header`. I do think doing it per component will make more sense as whether it's margin or padding will depend on the other styles.

Will push the change later this afternoon

Tom

**Comment by thamas** [comment]
Hi @tomhippen

It is great! Thanks!

**Comment by markconroy** [comment]
@tomphippen and @thamas can we close this issue?

**Comment by tomphippen** [comment]
Yes, if it does come up again it will need to be fixed per-component so would be a new issue.
