### ISSUE TITLE
Highlighted Small is using square ratio image, is this correct?

### ISSUE THREAD

**Issue by kjays** [lauriii/umami#116]
In the design, all cards have images at ratio 3x2 except for the two top right of the home page, which have square. The current version of the theme uses square ratio on all Highlighted Small view mode cards. Am I right in thinking we need to change 'Highlighted Small' to use 3 x 2 ratio and introduce a new View mode for the 2 x small square ratio images on cards at the top of the home page?

**Comment by markconroy** [comment]
I'm setting hightlighted small to now use the 3:2 ratio. I'll create a new view mode for the sqaure ones on the homepage.

**Comment by markconroy** [comment]
Update - highlighted small now uses the 3:2 ratio, but I didn't create a new view mode. 

So, the highlighted items at the top of the homepage are also using the 3:2 ratio.

Conversation here: https://drupal.slack.com/archives/C2HES6XQD/p1514995333000558
