### ISSUE TITLE
More accessible search in header

### ISSUE THREAD

**Issue by thamas** [lauriii/umami#119]
Don't hide "search" button and change the styling. 

On the jan 2 meeting (https://docs.google.com/document/d/1mF2C3K7HGg5rFv7E3UpmGcobSjDQLo18TH3BLN4ZWRo/edit#heading=h.nv9lhmyhuitv) we decided to go with option C design.

**Comment by thamas** [comment]
@kjays Please design hover/active states too and than provide access to the source sketch file!

**Comment by kjays** [comment]
@thamas This got me thinking whether we should address this styling issue as part of the global focus styles for fields first? At the moment we have standard browser outline styling of blue I believe? Do we want to style all text fields using outline or a custom approach?

**Comment by kjays** [comment]
But for starters. Here's the style guide snippet updated for our default styling:
<img width="876" alt="screen shot 2018-01-03 at 15 54 17" src="https://user-images.githubusercontent.com/31449148/34527717-6301be6e-f09e-11e7-91f4-6c2e178ca41d.png">

**Comment by fuzzbomb** [comment]
Good to see movement on this!  The invisible-but-operable button was a stability blocker IMO.

For focus, hover, active styles, I recommend addressing global styles first, then seeing if any exceptions are needed.

The trouble with the browser default styles, is they have occasionally been known to change abruptly between browser releases.  Remember back in the day when Chrome used an _orange_ outline?  Chrome's current pale blue might not pass the new WCAG 2.1 Graphics Contrast criterion.

I'll start an issue for global focus styles.

**Comment by fuzzbomb** [comment]
Note that WCAG 2.1 Graphics Contrast also applies to the resting state.  The grey input + button border should be at least 3:1 contrast to the background outside of the control.  The idea is that users have an idea of the extent of the clickable area (e.g. buttons often bigger padding than the text inside them)

**Comment by thamas** [comment]
@kjays Other text inputs and buttons (eg. on the login form) are very different than the search form. The question is what should be done to the alpha deadline. I hope the new design is more accessible that the current state so should be done. And we can improve it further if it is needed.

FYI Chrome provides the blue outline on the text input but Firefox displays nothing. 

I thinks focus / hover styles should be designed for this form.

**Comment by thamas** [comment]
So first round is in the dev branch! :)

- No focus / hover styles set yet!
- I set the font size a little bit smaller (0.875rem instead of 1rem) because I've found it to look better
- Styling leaks to the search page and possibly to other forms, that should be fixed too

![screenshot-2018-01-08 17-34-48](https://user-images.githubusercontent.com/1244043/34680777-4066faa4-f49a-11e7-8238-657d0b570386.png)

**Comment by fuzzbomb** [comment]
close this, follow-ups are at drupal.org in 

https://www.drupal.org/project/drupal/issues/2938194#comment-12466215
