### ISSUE TITLE
Copyright year: Install with correct year displayed

### ISSUE THREAD

**Issue by kjays** [lauriii/umami#121]
Install as current year or is there a 'better practice' method we can demo for setting the year? For example, we've used tokens before but I know that required a module.

https://www.drupal.org/project/drupal/issues/2904243#comment-12405148

**Comment by markconroy** [comment]
I've hardcoded 2018 into this. Since the content is coming from a YAML file `block.block.umami_disclaimer.yml`, I'm not sure how to set it dynamically.
```  umami_copyright:
    value: '&copy; 2018 Terms & Conditions'
    format: 'basic_html'```

This is fixed in the demo_umami repo - https://github.com/gareth-fivemile/demo_umami/commit/f4d76db283700e1318352def08470b48c2a9f0ef
