### ISSUE TITLE
Theme taxonomy term pages

### ISSUE THREAD

**Issue by kjays** [lauriii/umami#122]
I know @tomphippen has started this but I think the branch is local still

https://www.drupal.org/project/drupal/issues/2904243#comment-12405148

**Comment by tomphippen** [comment]
It's been pushed on `demo_umami` https://github.com/gareth-fivemile/demo_umami/commit/c8dd904147fdd60831a52fc0935e76dc9fa92bfc

**Comment by markconroy** [comment]
@tomphippen 

Is this okay to close now if it's pushed on another repo or do we need any theming to go with it?

**Comment by tomphippen** [comment]
It's ok to close, the change was just picking a view mode & adding a class to the existing theming would get picked up.
