### ISSUE TITLE
Theme search results

### ISSUE THREAD

**Issue by kjays** [lauriii/umami#123]
There was no design visual or styleguide produced for search results. I'll take a look at what's needed on this today. Might be feasible for me to go straight to theme for speed.

https://www.drupal.org/project/drupal/issues/2904243#comment-12405148

**Comment by tomphippen** [comment]
I've just pushed my initial work on this on a new branch https://github.com/lauriii/umami/tree/search-results

- I've gone for similar styles to the cards, on the basis we could have the featured image on the left
- the advanced search needs a bit of work, there's some empty divs (that don't appear to do anything) making flexbox a bit of an issue

**Comment by tomphippen** [comment]
The latest commit integrates the new design in the search box & does a few tweaks to get the results and advanced search matching those styles.
