### ISSUE TITLE
Articles cards display 'View recipe' rather than 'View article'

### ISSUE THREAD

**Issue by kjays** [lauriii/umami#125]
https://www.drupal.org/project/drupal/issues/2904243#comment-12405148

**Comment by markconroy** [comment]
The 'View recipe' link is now set to 'View {{ node.bundle }}'

https://github.com/lauriii/umami/commit/5dd292d8aed5c6778ba2057c96025bb5b47351cd

![screen shot 2018-01-04 at 11 58 41](https://user-images.githubusercontent.com/2183332/34562527-b689d8d4-f146-11e7-80da-7504d486d02c.png)
![screen shot 2018-01-04 at 11 58 51](https://user-images.githubusercontent.com/2183332/34562528-b6a7a0da-f146-11e7-8871-d760bcb8406e.png)
