### ISSUE TITLE
Focus styles for buttons

### ISSUE THREAD

**Issue by cehfisher** [lauriii/umami#132]
_Making a stand-alone ticket to tackle this accessibility issue._

From @fuzzbomb:
> Still need focus styles for buttons, currently, rely on color change only. (Can't recall whether the styles sheets are suppressing user agent defaults or not.)
> 
> Work has started on this with possibly too great a hover/focus change. Might want to wind this one in and keep the green/white but have a darker border. Or if folks like this (and I'm having second thoughts) then great.

From @kjays:
> Work has started on this with possibly too great a hover/focus change. Might want to wind this one in and keep the green/white but have a darker border. Or if folks like this (and I'm having second thoughts) then great.

**Comment by cehfisher** [comment]
I am seeing focus styles for buttons, but I think the issue is when a link <a> is used instead of a true <button> class.

Ex. page where this is happening: http://umami:8888/web/recipes
The pink "button" is actually a link (using <a>). Ideally, this would use a <button> tag and then you a new pink button class with proper focus styles, etc, would need to be created. In terms of accessibility <button> is always preferred.

**Comment by fuzzbomb** [comment]
I think some HMTL was stripped out of your comment, so I can't exactly make sense of what you meant.

> The pink "button" is actually a link 

It behaves as a link, so `<a>` is the correct element - that part is working fine. Do you think we should keep the "button" styling or make it more like the "View Recipe >" link style?  There might be some button styling classes we can re-use.

I see a focus style on this link.  In Firefox, it's the 1px dotted outline,  so it's not a very obvious focus style.  in Chromium it's the blue outline, and against the wooden table image, it's even harder to see than the Firefox one!

**Comment by markconroy** [comment]
I have that banner button/link set like this now:

default:
![screen shot 2018-01-12 at 16 48 38](https://user-images.githubusercontent.com/2183332/34885629-878e9d08-f7b8-11e7-9f2d-0243968b08d7.png)

hover/focus:
![screen shot 2018-01-12 at 16 48 42](https://user-images.githubusercontent.com/2183332/34885636-8de09846-f7b8-11e7-8104-bedeaaf3b18f.png)

Is that enough for this issue to close?

**Comment by cehfisher** [comment]
Was the mark-up changed to <button> and a new pink button class added? If not, this is a band-aid fix. Let me know if you want me to send in a PR for this or if you want to address at a later point.

**Comment by markconroy** [comment]
Hi Carrie,

I didn't change the markup, I just added a hover/focus state css to `.block-banner-block .field--name-field-content-link a`. There is no button class there, it's just styling the (entity reference field) field.

I'm happy to take your lead on suggestions.

**Comment by cehfisher** [comment]
This is one of those "best case scenario" type of fixes. Your fix is a great start, but much more we could do in the future. I'd say either close this ticket and we can reopen at at later date, or add a tag indicating that this ticket is a future improvement.

**Comment by markconroy** [comment]
I'll close for now, as issues are moving to Drupal.org.

**Comment by fuzzbomb** [comment]
Follow-up on d.o

https://www.drupal.org/project/drupal/issues/2938194
