### ISSUE TITLE
Create a text input focus style

### ISSUE THREAD

**Issue by cehfisher** [lauriii/umami#133]
_Making a stand-alone ticket to tackle this accessibility issue._

From @fuzzbomb:
> A text input focus style would be nice, e.g for the search form block.

From @kjays:
> @tomphippen and I started experimenting with this today

**Comment by fuzzbomb** [comment]
This is a good idea.  The caret does give you an indication of focus, but it's a very slight one.

**Comment by fuzzbomb** [comment]
This is underway at drupal.org, so we can close this in favour of 
https://www.drupal.org/project/drupal/issues/2938194
