### ISSUE TITLE
Add icons to the message statuses

### ISSUE THREAD

**Issue by cehfisher** [lauriii/umami#134]
_Making a stand-alone ticket to tackle this accessibility issue._

From @fuzzbomb:
> The message status (error, warning, info) are currently distinguished by colour alone. Icons would be the easiest solution here. I really like the full-width background, that could help draw attention to the message area.

From @kjays:
> @thamas has done some work on this and simultaneously I did similar work but using the same link styles as the body area with colour variations. I need to re-implement my work for the links only since they conflicted on merge

**Comment by thamas** [comment]
@cehfisher It was done by #48 

I checked again, icons are displayed, but link style has changed. 

I close it but feel free to reopen if you see something to be done.

**Comment by thamas** [comment]
Output generated by styleguide module:
![screenshot-2018-01-05 11-44-06](https://user-images.githubusercontent.com/1244043/34611312-3be7c82c-f225-11e7-898b-c854b6117e14.jpg)

**Comment by cehfisher** [comment]
Thanks for checking! It sounded like this might have been regressed on the last feature branch. Glad it was not. :)

**Comment by fuzzbomb** [comment]
The icons and underlined links in the screenshot above are the right idea.
