### ISSUE TITLE
Review site in high contrast mode

### ISSUE THREAD

**Issue by cehfisher** [lauriii/umami#137]
Probably not the highest priority, but want to make sure this gets a review as well.

From @fuzzbomb:
> The way the main nav uses tansparent bottom borders, is likely to break in windows high contrast mode. color: transparent is overridden, so all items will be underlined. I should test that for real.
> 
> On a positive note, there are very few instances of the transparent keyword in the CSS, so we're off to a good start here with Windows High Contrast themes :-)

**Comment by fuzzbomb** [comment]
We should stop conveying different states by toggling colour between transparent and some visible colour.

As far as I'm concerned, `transparent` is a colour, and if active/hover/focus states are solely swapping a 3px transparent border for a 3px red border then that's a failure of WCAG 1.4.1 Use of Color.

**Comment by fuzzbomb** [comment]
We actually have this problem in Seven, for the secondary tabs.  Must file an issue against the Seven theme for that....

**Comment by thamas** [comment]
@fuzzbomb it would be great if you could suggest an other solution which is right for a11y too.

**Comment by fuzzbomb** [comment]
Let's close this one, effectively postponing it.  The MVP theme was committed to core a while back.  Meanwhile, the core plan for supporting Windows High Contrast mode hasn't gone beyond the fact-finding stage yet. 

I'll add a task to review Umami in the Drupal.org plan  - [Make core themes more robust in Windows High-Contrast mode](https://www.drupal.org/project/ideas/issues/2894237)
