### ISSUE TITLE
Button erroneously has .visually-hidden class

### ISSUE THREAD

**Issue by cehfisher** [lauriii/umami#139]
Need to review to see if this is still an issue and if there are any other instances of this bug.

From @fuzzbomb:
> Something really confusing: there's a form_alter which adds .visually-hidden to the search form submit button. For a sighted keyboard user the button will be operable, but not perceivable. Could also cause difficulty for touch screen users, speech control, or users who input text with something other than a keyboard. A visible button is safer.

**Comment by fuzzbomb** [comment]
This one is high priority.  We have a new design proposal in #119 which makes the button visible again.

**Comment by thamas** [comment]
Let's do it in #119!
