### ISSUE TITLE
Menu toggle button gets two click handlers on some pages.

### ISSUE THREAD

**Issue by fuzzbomb** [lauriii/umami#143]
On some pages (e.g. homepage) the menu button doesn't work.
On others (e.g. the search page) it works.

It's getting a toggle handler assigned twice, needs a jQuery `once()` filter.

**Comment by thamas** [comment]
@fuzzbomb Is it about the latest version: https://github.com/lauriii/umami/commit/a15efc0b25c5aee7ee2ec57fb1f5723854e08db4 ? (FYI the latest version does not use jQuery.)

If yes, please add a comment to #131!

If not, please check that (and comment #131 if needed)!
