### ISSUE TITLE
H3 vs H4 heading styles

### ISSUE THREAD

**Issue by cehfisher** [lauriii/umami#145]
_Breaking this subtask off a comment from @lyndsey in #110. Can verify the margin is the only visual difference between the two headings._

H5 and H6 are fine now however in body content h3 and h4 are the same size (screenshot below). I have:
h2 1.77rem
h3 1.33rem
h4 1.33rem
h5 1.125rem
h6 1rem

Suggestion: change h3 to 1.5 or 1.6rem.
Tested this on a few pages and couldn't find a style issue with either size option.
 
![headings](https://user-images.githubusercontent.com/15240149/34654199-e33c79bc-f3bd-11e7-8714-d29678f468d9.png)

**Comment by thamas** [comment]
I found that 1.5rem fits better, so set that for h3.

![screenshot-2018-01-08 11-52-46](https://user-images.githubusercontent.com/1244043/34667742-a008d76e-f46a-11e7-9da6-37f0115a33cf.png)

**Comment by cehfisher** [comment]
Looks good to me locally. Thanks! (cc @lyndsey)
