### ISSUE TITLE
Use extend to create menu-main.html.twig template

### ISSUE THREAD

**Issue by thamas** [lauriii/umami#149]
Extend menu.html.twig instead of duplicating it.

**Comment by tomphippen** [comment]
Is the solution to this one editing menu.html.twig to add `.setAttribute('data-drupal-selector',menu_classes)` to level 0 menus and remove menu-main.html.twig.

It's the only difference in files and I can't see that it would have any negative effects if other menus get a data attribute

**Comment by ckrina** [comment]
Closing in favour of D.O. issue: https://www.drupal.org/project/drupal/issues/2936880
