### ISSUE TITLE
.form-actions and .form-submit might be too generic in search.css

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#151]
```
/* Search submit */
.form-actions {
  display: inline-flex;
}
.form-submit {
  padding: 0.6em 1.25em 0.4em;
  border: 1px solid #dbdbdb;
  border-radius: 0 3px 3px 0;
  font-size: 0.875rem;
  background-color: #fff;
  color: #000;
}
```

I have a feeling this is a little bit generic to be in the search.css file. It's going to affect _every_ .form-submit and .form-actions, rather than just the search-block-form one.

Should we make it a bit more specific here or move it to a form-specific partial?

**Comment by tomphippen** [comment]
@markconroy I'm closing this issue as I fixed it doing the work in #152
