### ISSUE TITLE
Style the "skip to main content" link

### ISSUE THREAD

**Issue by fuzzbomb** [lauriii/umami#154]
The skip link is currently unstyled, and it causes a content jump when focusing it.

It has the core `.visually-hidden.focusable` classes, so the functionality is otherwise fine.

As a first cut, we could try copying the style from Bartik/Seven, and see if it still works here.  That's a good style because it sits well next to the toolbar.  Maybe change the colour to resemble one of the existing Umami buttons.

Later we could design a custom style if we like.

**Comment by markconroy** [comment]
deploying this now: 
![screen shot 2018-01-12 at 16 31 45](https://user-images.githubusercontent.com/2183332/34884905-1e14942e-f7b6-11e7-8a72-419cc061ea02.png)

**Comment by fuzzbomb** [comment]
Great!
