### ISSUE TITLE
RSS icon needs better position

### ISSUE THREAD

**Issue by fuzzbomb** [lauriii/umami#155]
Found during site review at the NWDUG meetup (copying from the google doc, https://docs.google.com/document/d/1JvRiVyx-xob6UC5ajW7DxNg9qkEg2uKhOrW3NUOEE2w/edit)

"Term page RSS icon is too close to the footer"

Screenshot: 
![umami-rss-icon-too-close-to-footer](https://user-images.githubusercontent.com/1243005/34853720-3faddc00-f72d-11e7-9850-d44b508cda26.png)

**Comment by markconroy** [comment]
I don't think those icons are supossed to be there. They are certainly not in the designs. I'll create an issue on the demo_umami repo.
