### ISSUE TITLE
Article author + date information - add a visual separator?

### ISSUE THREAD

**Issue by fuzzbomb** [lauriii/umami#156]
Found during site review at the NWDUG meetup, (copying from the google doc, https://docs.google.com/document/d/1JvRiVyx-xob6UC5ajW7DxNg9qkEg2uKhOrW3NUOEE2w/edit)

> “by Holly Foat 9th January 2018” split node author name and date with a divider.

Screenshot:
![umami-article-author-date-styling-needs-separator](https://user-images.githubusercontent.com/1243005/34853901-37d5b93e-f72e-11e7-9401-a162ef84d075.png)

Do we need a separator between author name and time?  I recall some coloured dot separators from an earlier design - maybe these were between tags.  I'm not up to date with whether those survived in later designs, so I'm leaving this issue here in case it's an omission.

**Comment by tomphippen** [comment]
@fuzzbomb I think this had just been missed rather than deliberately removed, I've added them in
