### ISSUE TITLE
 Components: View Mode: Magazine Promo Small

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#47]
We might need a more generic name than "Magazine Promo Small"

**Comment by mariohernandez** [comment]
How about "Featured Promo"?

**Comment by markconroy** [comment]
I can't remember what view mode this is to be honest? Can someone pop a screenshot in here if we still need to have work done on this?

**Comment by ckrina** [comment]
Closing, already addressed.

![small-promo](https://user-images.githubusercontent.com/2225966/36046166-50e7840a-0dd8-11e8-806a-58f17274365b.png)
