### ISSUE TITLE
Components: Navigation: More Link

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#50]

**Comment by thamas** [comment]
What is the more link @ckrina? Is it the buttons section in the styleguide pdf?

**Comment by markconroy** [comment]
It's the 'read more' (view recipe in this case) link as far as I know.
![screen shot 2017-10-12 at 20 46 52](https://user-images.githubusercontent.com/2183332/31515827-8789e2a8-af8e-11e7-9418-048758bf56cf.png)

**Comment by thamas** [comment]
OK, thx!
