### ISSUE TITLE
Components: Image Styles

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#63]
highlighted-large - used on the "Highlighted Top/Bottom" view modes See: #24 #25
highlighted-small - used on the "Highlighted Small" view mode See: #26
body-image - images uploaded via the WYSIWYG See: ??

**Comment by markconroy** [comment]
Do we need to use responsive images here?

**Comment by ckrina** [comment]
I'd say... yes? I'd expect the same markup in a styleguide. Also, it can force us decide some breakpoints and I think that's good. Anyway, I don't have a strong preference and I'd be fine with css-scaled images on the styleguide.

**Comment by mariohernandez** [comment]
Are we doing any drupal configuration of responsive images module in this issue?  If so, which image fields are we configuring?

**Comment by ckrina** [comment]
I'd say at least the ones for:
- highlighted-large - used on the "Highlighted Top/Bottom" view modes
- highlighted-small - used on the "Highlighted Small" view mode

Not sure about the body-image one since I think it have other implications. I'd create a solo issue for that one when we start the Article detail styling. And the same for the ones on banners: let's keep it separated so issues are less dependant from others.

**Comment by mariohernandez** [comment]
Great!  Thank you @ckrina.  I'll start with responsive images and image styles.

**Comment by mariohernandez** [comment]
From our last call it looks like most images are aspect ratio driven so I think it makes more sense to use the aspect ratio as the image style name as this will make them more reusable.

**Comment by ckrina** [comment]
+1 to the aspect ratio for the name

**Comment by mariohernandez** [comment]
Created image styles as well as responsive image styles.  Updated Article and Recipe content type image fields to use newly created image styles.
PR can be seen here: https://github.com/gareth-fivemile/demo_umami/pull/12

**Comment by thamas** [comment]
I merged the related config changes: https://github.com/gareth-fivemile/demo_umami/pull/12

We can / should check now much easier that everything is set as needed.

**Comment by markconroy** [comment]
Can this be closed @thamas & @mariohernandez?

**Comment by mariohernandez** [comment]
Closing as this has been merged by @thamas above.
