### ISSUE TITLE
Components: Navigation: Tabs

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#64]

**Comment by thamas** [comment]
Are we talking about the Drupal's content tabs (View, Edit etc.)?

**Comment by markconroy** [comment]
Yes, 

View | Edit | Delete | Devel

Login | Create Account | Forgot Password

etc

**Comment by thamas** [comment]
OK.  As I know there is no design for that. So it will be designed by the one who creates this component?

**Comment by markconroy** [comment]
I guess so. 

I have a standard design for mine that I use on all my sites now. Basically, black background, white links, and place at the top of the page under the toolbar so they are always at the same place no matter whether they are the user login/password links or the node edit/view links.
login links:
![screen shot 2017-10-13 at 10 39 53](https://user-images.githubusercontent.com/2183332/31540208-e48a4032-b002-11e7-87c7-22d20cefe20e.png)

edit/view links:
![screen shot 2017-10-13 at 10 37 59](https://user-images.githubusercontent.com/2183332/31540169-ca157258-b002-11e7-8d55-c0746a99c1b5.png)

**Comment by thamas** [comment]
Designs from @kjays 
![umami - admin logged in tabs with status msg](https://user-images.githubusercontent.com/1244043/32334526-ed3030f0-bfea-11e7-8461-073a359699d3.jpg)
![umami - admin logged in tabs](https://user-images.githubusercontent.com/1244043/32334529-ed7415b8-bfea-11e7-9e6f-9376cb5a2c04.jpg)

**Comment by thamas** [comment]
Designs from @k
![umami - admin logged in tabs with status msg](https://user-images.githubusercontent.com/1244043/32334526-ed3030f0-bfea-11e7-8461-073a359699d3.jpg)
![umami - admin logged in tabs](https://user-images.githubusercontent.com/1244043/32334529-ed7415b8-bfea-11e7-9e6f-9376cb5a2c04.jpg)
