### ISSUE TITLE
Umami Theme - Base Theme

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#70]
Now that work has started we need to standardise on class names. So far I have been using the same class names that classy gives us. What are we going to use - classy, stable, none. 

This was discussed in Vienna:

Pros for Classy (or stable):
- Developers are used to these class names from Drupal 6 to Drupal 7 to Drupal 8, so might make it easier for new developers to come on board in the earlier stages, but also after it is launched
- Drupal recommends this approach; it might not be a great thing for us to **not** follow our own suggestions

Cons:
- Classy and stable may not be available in Drupal 9
- If this is the case, the theme might need re-factoring then

Thoughts?

**Comment by thamas** [comment]
As I started to work on components using the markup (and class names) comes from classy I feel that there are a lot of stuff not needed for this design and also there are things that are not consistent. E.g. our CSS Coding Standards says that we should use BEM style class naming but I miss it some times or feel it is based on CMS logic not on thje logic of the comtent structure we have.

So if we want this theme not just for those who looks it from outside but for those too who check the code too we should refactor and clean up things to be able to say that we provide "best practices".

**Comment by thamas** [comment]
"We should use Classy as the base theme" – it was recorded [to the meeting log](https://docs.google.com/document/d/1mF2C3K7HGg5rFv7E3UpmGcobSjDQLo18TH3BLN4ZWRo/edit#) from today.
