### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#71]
Folder structure - we now have a decent amount of work done on the theme/styleguide. How is the folder structure working? Anything we need to change immediately, or should we just keep working for now?

**Comment by thamas** [comment]
I think we can keep working for now and modify structure if needed. But we also have to have a plan. As we plan to connect this living styleguide with Drupal we should build a structure which makes sense for that. Which makes easy to find the related templates both in the styleguide and in drupal theme template structure.

Also becuause this is a CSS styleguide and we write a lot of CSS we should keep in mind and reflect to Drupal's CSS Coding Standards which has a structure recommendation based on SMACSS.

**Comment by markconroy** [comment]
This issue has been taken care of from discussions at yesterday's meeting - basically follow a SMACSS-style folder structure.
