### ISSUE TITLE
Make available external JS libs in KSS

### ISSUE THREAD

**Issue by thamas** [lauriii/umami#78]
JS behaviors wont work in the current KSS Styleguide because we have no way to add external libraries which available in Drupal such as jQuery. We can't use Drupal.behaviors either for the same reason.

**Comment by thamas** [comment]
With this solution (what I learned from @mariohernandez repos) the Drupal js files became available when we move our Umami theme (including the sytle guide) into a Drupal installation (/codebase).

**Comment by markconroy** [comment]
@thamas 

if that is the case (it works when inside a drupal folder), maybe we should add that sooner rather than later?

It will also mean we can export config that will be needed there and create any new config/fields etc that we reaslise we need as we are building.

**Comment by thamas** [comment]
@markconroy Yes. I worked on these tasks because I think it would be good to add as soon as we can.
