### ISSUE TITLE
Configure the font family to fall back to appropriate system fonts

### ISSUE THREAD

**Issue by kjays** [lauriii/umami#87]
There is the chance that Alpha will not be able to use web fonts and we should have solid system font fall back in place anyway.

**Comment by thamas** [comment]
Independently of web fonts status we should set a correct system font set I think. Something like: https://css-tricks.com/snippets/css/system-font-stack/

**Comment by ckrina** [comment]
I agree with @thamas, even we end up using another font, a system fonts needs to be defined as fallback. Which ones fits better for you @kjays ?

**Comment by kjays** [comment]
A better description there, thank you!

That recent article you've shared on system font is interesting but I've not taken that approach before, I'm not sure how much testing that leaves us across OS types and even versions since the fonts are going to keep switching in look and feel. I'd be interested in other's experience with this approach if you've tried it. It might 'just work' :)

Otherwise, it's over to the web safe font stacks as the intro in that article says and we try a few ideas out.

**Comment by kjays** [comment]
I think a good starting point is a simple font stack along the lines of:

font-family: 'Open sans', Verdana, sans-serif;
and
font-family: 'Scope One', Georgia, serif;

This doesn't really consider Linux very specifically other than the sans-serif/serif fall back but once we've got further down the road this can be much enhanced if we want to.

I'll create a pull request now. Attached is roughly how the above would look for users with Verdana and Georgia

![umami - article - web safe georgia and verdana](https://user-images.githubusercontent.com/31449148/32134186-bad9a33e-bbdf-11e7-8fc6-fd197825f381.jpg)
