### ISSUE TITLE
How to workaround search block in top region on desktop but header on mobile

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#90]
We need to account for how we layout the top region and header region, since on mobile they seem to share blocks - notably the search block.

See https://github.com/lauriii/umami/pull/88 for details.

Related #56 

![screen shot 2017-10-28 at 18 16 56](https://user-images.githubusercontent.com/2183332/32136789-3edb94a4-bc0c-11e7-9320-096cf34d4156.png)
![screen shot 2017-10-28 at 18 17 09](https://user-images.githubusercontent.com/2183332/32136790-3efb8502-bc0c-11e7-9ca0-cb6e177a89c4.png)

**Comment by thamas** [comment]
Do we have to have separate regions for these?

If the elements had a common parent we could vary their order with flexbox or CSS Grid (ie11 supports that part too). 

If we want to keep the separation a workaround can be that we duplicate some elements in different regions and show / hide the ones needed or not inside media queries.

**Comment by thamas** [comment]
How about it?

https://codepen.io/thamas/pen/MOBVNY

**Comment by mariohernandez** [comment]
I think flexbox makes sense.

**Comment by thamas** [comment]
@kjays Please check it! I did not find any design about the search on narrow screens so I've chosen the simplest solution: just a link to the search page. I'think it is OK (for the first version at least) but I'd like to know your opinion too.

**Comment by thamas** [comment]
Thank you all, for the reactions! Could someone check the pen in IE11? I think it should be OK, but I cannot test it.

**Comment by markconroy** [comment]
Here's two screenshots of IE11 on Windows 10 from BrowserStack.com.


![screen shot 2017-11-27 at 19 17 43](https://user-images.githubusercontent.com/2183332/33284657-b91b98d8-d3a7-11e7-9054-d6e8fbdf3fd3.png)
![screen shot 2017-11-27 at 19 18 01](https://user-images.githubusercontent.com/2183332/33284658-b93b5bdc-d3a7-11e7-82ab-0033bbc057cc.png)

**Comment by thamas** [comment]
@markconroy thanks for the IE11 test! It seems to work! :)

So I'll do it!

**Comment by thamas** [comment]
Still have to save config changes but after that it will be "needs review". :)
https://monosnap.com/file/tVswF33hAyZfP5UnK8nHXj1rJwio4C#

**Comment by thamas** [comment]
Just wrote a new issue because of the experience working on this: #113
