### ISSUE TITLE
Abandon the Styleguide

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#92]
The intention to use a styleguide was so that we could demonstrate a "best practice" approach to theming and so that others looking at our theme would follow our example.

However, due to limitations in Drupal Core, for example not having access to the styleguide's namespaces without something like Components module in core, I feel that we will not be building a "best practice" theme, but rather doing our best with what we have and making lots of compromises.

For this reason, I think it is safer for us to stop trying to develop a styleguide and to start developing a standard Drupal theme, just like Bartik has done.

This idea had agreement from those who attended today's weekly meeting.

**Comment by kjays** [comment]
Agreed, this feels like something that could be returned to given more supporting progress in core but for now, because we want to speed things along, it's one thing less to hit blockers or speed humps on.

**Comment by thamas** [comment]
Agree.

**Comment by ckrina** [comment]
In my head building the style guide wasn't only a best practice showcase, but also a way of speeding the theme development. But it happened to be the opposite.
So as I said on the meeting, I agree on moving to a classical theming methodology regarding templates to try reach 8.5. But I'd like to keep the "components" structure for the CSS to be more future-friendly.

**Comment by thamas** [comment]
We also have to follow Drupal's CSS Coding Standards in our file structure: https://www.drupal.org/docs/develop/standards/css/css-file-organization-for-drupal-8

**Comment by markconroy** [comment]
Four out of or core of 6 are in agreeement, so I am going to move with it.

Thanks for the comments.
