### ISSUE TITLE
Write Access to Master Branch

### ISSUE THREAD

**Issue by markconroy** [lauriii/umami#93]
During today's weekly meeting, a topic was proposed about how we can develop faster - especially with a deadline coming up in 2 weeks.

I proposed that we give write access to the master branch to people actively working on the theme, namely:

- Lauri
- Mark
- Christina
- Keith
- Thamas
- Mario

At the moment, waiting for reviews of pull requests and then making changes and waiting for a new review is taking too long and we feel we are not getting enough done. If we can write directly to the master branch we can work quicker.

To alleviate the potential for coding standards to be broken, I suggest we do a weekly code review of everything that was committed that week.

Any thoughts?

**Comment by kjays** [comment]
And Gareth who has shared his credentials in Slack also.

**Comment by thamas** [comment]
+1

**Comment by markconroy** [comment]
We now have write access to master branch. 

Please work on `dev` branch and we can merge periodically.
