### ISSUE TITLE
General styles: Layout for recipe content type using experimental core field layout module

### ISSUE THREAD

**Issue by kjays** [lauriii/umami#98]
We discussed the requirements for a core theme to support the potential for fields to be moved around by a user via the manage display settings for the recipe content type. My recollection of that conversation was that whilst we may not be able to produce styling that will aways look great given the repositioning of a field, we should not theme in such a way so as to prevent this happening.

This issue exists since we have specific layouts with styled wrappers around groups of fields.

I believe the recommended solution by Lauri was to use the experimental layout module.

Attached is a screenshot of a prototype layout that supports this approach for recipe content type. This issue covers work on theming out the recipe content type's layout using this method ready for review.

![screen shot 2017-11-08 at 16 22 55](https://user-images.githubusercontent.com/31449148/32573352-97f817ee-c4c5-11e7-9ebe-ed1851b1fd32.png)

**Comment by kjays** [comment]
I'm parking this so that we can go through it in our next meeting. This needs more thinking through based on some of the gotchas I'm starting to wrap my head around.

**Comment by ckrina** [comment]
Closing in favour of the D.O. issue: https://www.drupal.org/project/drupal/issues/2943675
