### ISSUE TITLE
Embedding fonts and additional font weights for open sans

### ISSUE THREAD

**Issue by kjays** [lauriii/umami#99]

**Comment by mariohernandez** [comment]
Can please I get more details on what needs to happen on this issue?  Thanks.

**Comment by ckrina** [comment]
Not sure if this issue might collide with the licence issues (about fonts and images). @kjays might have more info.

- https://www.drupal.org/project/drupal_lwg/issues/2916161
- https://www.drupal.org/node/2919135

**Comment by mariohernandez** [comment]
Hi @kjays do you have any info on @ckrina's comment above?  Can this be closed?

**Comment by ckrina** [comment]
Closing this issue in favor the D.O. issue. Added a quick patch there ready to review: https://www.drupal.org/project/drupal/issues/2943657.
